
function copyText(txt){navigator.clipboard?.writeText(txt).then(()=>alert('Copied!'))}
function initQuiz(data){ if(!data||!data.length) return; let step=0,score=0; const qText=document.getElementById('qText'); const qButtons=document.getElementById('qButtons'); const qResult=document.getElementById('qResult'); function render(){ const q=data[step]; qText.innerText=q.q; qButtons.innerHTML=''; q.options.forEach((opt,i)=>{ const b=document.createElement('button'); b.className='btn'; b.style.margin='6px'; b.innerText=opt; b.onclick=()=>{ if(i===q.answer){ qResult.innerText='Correct! '+(q.explain||''); score++; } else qResult.innerText='Not quite. '+(q.explain||''); setTimeout(()=>{ step++; qResult.innerText=''; if(step>=data.length){ qText.innerText='Done! Score: '+score+'/'+data.length; qButtons.innerHTML=''; } else render(); },900); }; qButtons.appendChild(b); }); } render(); }
function addFlower(emoji){ const el=document.getElementById('bouquetDisplay'); if(!el) return; if(el.innerText==='Tap flowers to add') el.innerText=''; el.innerText += emoji + ' '; }
function clearBouquet(){ const el=document.getElementById('bouquetDisplay'); if(el) el.innerText=''; }
function shareBouquet(){ const el=document.getElementById('bouquetDisplay'); if(el) copyText('A bouquet for you: '+(el?.innerText||'')); }
function randomIdea(listId,targetId){ const list=window[listId]; if(!list) return; const pick=list[Math.floor(Math.random()*list.length)]; document.getElementById(targetId).innerText=pick; }
function shuffleIdeas(listId,targetId){ const list=window[listId]; if(!list) return; for(let i=list.length-1;i>0;i--){ const j=Math.floor(Math.random()*(i+1)); [list[i],list[j]]=[list[j],list[i]]; } randomIdea(listId,targetId); }
function startCountdown(isoStart){ const start=new Date(isoStart); const el=document.getElementById('timeSince'); if(!el) return; function update(){ const now=new Date(); const diff = Math.max(0, now - start); const days=Math.floor(diff/(1000*60*60*24)); const hours=Math.floor((diff/(1000*60*60))%24); const minutes=Math.floor((diff/(1000*60))%60); const seconds=Math.floor((diff/1000)%60); el.innerText = days+'d '+hours+'h '+minutes+'m '+seconds+'s'; } update(); setInterval(update,1000); }

